log:
  level: debug
  job_level: debug

runner:
  file: .runner
  env_file: .env
  capacity: 1
  timeout: 3h
  shutdown_timeout: 1h
  insecure: false
  fetch_timeout: 5s
  labels: ["linux-amd64:docker://ghcr.io/btbn/ffmpeg-builds/base:latest"]

cache:
  enabled: true
  dir: actcache

host:
  workdir_parent: act

container:
  network: "runnernet"
  enable_ipv6: false
  privileged: false
  options:
  workdir_parent:
  force_pull: true
  force_rebuild: true
